services:
  identity-service:
    build:
      context: ./identity-service
    container_name: identity-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/bigbankdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pg
      APP_JWT_SECRET: dev-only-change-me-use-64-plus-chars-abcdefghijklmnopqrstuvwxyz0123456789
      APP_JWT_EXPIRATION_MS: 86400000
    restart: unless-stopped

  banking-service:
    build:
      context: ./banking-service
    container_name: banking-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/bigbankdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pg
      APP_JWT_SECRET: dev-only-change-me-use-64-plus-chars-abcdefghijklmnopqrstuvwxyz0123456789
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      APP_INTERNAL_API_KEY: dev-internal-key-change-me      
    restart: unless-stopped
    depends_on:
      - activemq

  activemq:
    image: apache/activemq-classic:6.1.4
    container_name: activemq
    ports:
      - "8161:8161"   # Web console
      - "61616:61616" # JMS OpenWire
    environment:
      ACTIVEMQ_CONNECTION_USER: admin
      ACTIVEMQ_CONNECTION_PASSWORD: admin
    restart: unless-stopped

  interest-service:
    build:
      context: ./interest-service
    container_name: interest-service
    ports:
      - "8084:8084"
    environment:
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
      BANKING_SERVICE_BASE_URL: http://banking-service:8083
      APP_BANKING_BASE_URL: http://banking-service:8083
      APP_INTERNAL_API_KEY: dev-internal-key-change-me
    depends_on:
      - activemq
      - banking-service
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      GATEWAY_ROUTES_IDENTITY: http://identity-service:8082
      GATEWAY_ROUTES_BANKING: http://banking-service:8083
    restart: unless-stopped
    depends_on:
      - identity-service
      - banking-service
      - interest-service
