spring.application.name=interest-service
server.port=8084

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

app.jms.interest-queue=interest.accrual.queue
app.banking.base-url=http://localhost:8083
app.internal.api-key=dev-internal-key-change-me

management.endpoints.web.exposure.include=health,info