spring.application.name=banking-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/bigbankdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=pg
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.cache.type=caffeine
# Applies to all cache regions (accounts, customers)
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=5m
spring.cache.cache-names=accounts,customers


spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

app.jms.interest-queue=interest.accrual.queue
app.internal.api-key=dev-internal-key-change-me


logging.level.org.springframework.cache=TRACE


management.endpoints.web.exposure.include=*

app.jwt.secret=dev-only-change-me-use-64-plus-chars-abcdefghijklmnopqrstuvwxyz0123456789
